#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require '../lib/utils'

base = File.expand_path('..', File.dirname(__FILE__))
versions = versions_for_build
versions.each do |version|
  puts "\n--------------------------------\nBuilding Version #{version}\n\n"

  dir = File.join(base, 'build', "Version#{version}")
  FileUtils.rm_r dir if File.exist?(dir)
  FileUtils.mkdir_p dir

  system("ruby src/generate.rb -v #{version} ghpages")
end
