#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'
require '../lib/utils'

def write_root_page(dir, versions, latest, development)
  puts "\n--------------------------------\nGenerating Root Page: #{dir}\n\n"
  FileUtils.rm_r dir if File.exist?(dir)
  FileUtils.mkdir_p dir

  FileUtils.ln_s('./figures', File.join(dir, 'figures'), relative: true)

  fn = File.join(dir, 'index.md')
  puts "Generating file: #{fn}"
  File.open(fn, 'w') do |f|
    f.puts <<~EOT
      ---
      title: MTConnect
      nav_order: 1
      has_children: true
      layout: default
      ---

      # MTConnect SysML Model Documentation

      ## Latest Versions

      * [Latest Version (#{latest})](/Version#{latest}/)
      * [Development Version (#{development})](/Version#{development}/)

      ## All Versions

    EOT
    versions.sort.reverse.each do |version|
      f.puts "* [Version #{version}](/Version#{version}/)"
    end

    f.puts <<EOT

---

This MTConnect model is normative and any content that is informative
and/or is defined for descriptive purposes only has been either
stereotyped as <<informative>> or documented as "Notes".

---

*AMT* owns the copyright in this MTConnect Specification or
Material. *AMT* grants to you a non-exclusive, non-transferable,
revocable, non-sublicensable, fully-paid-up copyright license to
reproduce, copy and redistribute this MTConnect Specification or
Material, provided that you may only copy or redistribute the
MTConnect Specification or Material in the form in which you received
it, without modifications, and with all copyright notices and other
notices and disclaimers contained in the MTConnect Specification or
Material.

If you intend to adopt or implement an MTConnect Specification or
Material in a product, whether hardware, software or firmware, which
complies with an MTConnect Specification, you shall agree to the
MTConnect Specification Implementer License Agreement ("Implementer
License") or to the MTConnect Intellectual Property Policy and
Agreement ("IP Policy"'). The Implementer License and IP Policy each
sets forth the license terms and other terms of use for MTConnect
Implementers to adopt or implement the MTConnect Specifications,
including certain license rights covering necessary patent claims for
that purpose. These materials can be found at
[www.MTConnect.org](https://www.MTConnect.org), or or by contacting
[info@MTConnect.org](mailto:info@MTConnect.org).

MTConnect Institute and *AMT* have no responsibility to identify
patents, patent claims or patent applications which may relate to or
be required to implement a Specification, or to determine the legal
validity or scope of any such patent claims brought to their
attention. Each MTConnect Implementer is responsible for securing its
own licenses or rights to any patent or other intellectual property
rights that may be necessary for such use, and neither *AMT* nor
MTConnect Institute have any obligation to secure any such rights.

This Material and all MTConnect Specifications and Materials are
provided "as is" and MTConnect Institute and *AMT*, and each of their
respective members, officers, affiliates, sponsors and agents, make no
representation or warranty of any kind relating to these materials or
to any implementation of the MTConnect Specifications or Materials in
any product, including, without limitation, any expressed or implied
warranty of noninfringement, merchantability, or fitness for
particular purpose, or of the accuracy, reliability, or completeness
of information contained herein. In no event shall MTConnect Institute
or *AMT* be liable to any user or implementer of MTConnect
Specifications or Materials for the cost of procuring substitute goods
or services, lost profits, loss of use, loss of data or any
incidental, consequential, indirect, special or punitive damages or
other direct damages, whether under contract, tort, warranty or
otherwise, arising in any way out of access, use or inability to use
the MTConnect Specification or other MTConnect Materials, whether or
not they had advance notice of the possibility of such damage.

EOT
  end

  fn = File.join(dir, '_config_version.yml')
  puts "Generating file: #{fn}"
  File.open(fn, 'w') do |f|
    f.puts "title: MTConnect SysML Model Documentation"
    f.puts "comment_url: #{ENV['COMMENT_URL'] || 'https://projects.mtconnect.org'}"
  end
end

def build_version(base, src, dest, version = nil)
  puts "\n--------------------------------\nBuilding #{src} -> /#{dest}\n\n"

  source = File.join(File.dirname(__FILE__), 'tmp', "#{src}/")
  destination = File.join(base, 'deploy', "#{dest}/")

  if version
    FileUtils.rm_r source if File.exist?(source)
    FileUtils.mkdir_p source
    FileUtils.rm_r destination if File.exist?(destination)
  
    FileUtils.ln_s(File.join(base, "Version#{version}", "MTConnectSysMLModel.xml"), File.join(source, "MTConnectSysMLModel_V#{version}.xml"))
    Dir[File.join(base, 'build', "Version#{version}", '*')].each do |d|
      FileUtils.ln_s(d, File.join(source, File.basename(d)))
    end
  end

  %w{_config.yml _includes _layouts _sass 404.html assets}.each do |d|
    FileUtils.ln_s(d, File.join(source, d), relative: true)
  end

  dest = '.' if dest.empty?
  command = "bundle exec jekyll build -s #{source} --config ./_config.yml,#{source}_config_version.yml --baseurl /#{dest} -d #{destination}"
  puts "Running command: #{command}"
  system(command) || raise(command)
end

base = File.expand_path('..', File.dirname(__FILE__))
versions, latest, development = versions_for_build

write_root_page(File.join(File.dirname(__FILE__), 'tmp', 'Root'), versions, latest, development)
build_version(base, 'Root', '',)
system("cat ../deploy/index.html")

versions.each do |version|
  build_version(base, "Source#{version}", "Version#{version}", version)
end
