#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'
require '../lib/utils'

base = File.expand_path('..', File.dirname(__FILE__))
versions = versions_for_build
versions.each do |version|
  puts "\n--------------------------------\nBuilding Version #{version}\n\n"

  source = File.join(File.dirname(__FILE__), 'tmp', "Source#{version}/")
  destination = File.join(base, 'deploy', "Version#{version}/")

  FileUtils.rm_r source if File.exist?(source)
  FileUtils.rm_r destination if File.exist?(destination)

  FileUtils.mkdir_p source

  %w{_config.yml _includes _layouts _sass 404.html assets}.each do |d|
    FileUtils.ln_s(d, File.join(source, d), relative: true)
  end
  FileUtils.ln_s(File.join(base, "Version#{version}", "MTConnectSysMLModel.xml"), File.join(source, "MTConnectSysMLModel_V#{version}.xml"))

  Dir[File.join(base, 'build', "Version#{version}", '*')].each do |d|
    FileUtils.ln_s(d, File.join(source, File.basename(d)))
  end

  system("bundle exec jekyll build -s #{source} --config ./_config.yml,#{source}/_config_version.yml -b /Version#{version} -d #{destination}")
end