#!/usr/bin/env ruby

require 'fileutils'

if ARGV.length == 1
  version = ARGV[0]
  source = "./tmp/Source#{version}"
  destination = "../deploy/Version#{version}/"
  base = "/Version#{version}"
else
  source = "./tmp/Root"
  destination = "../deploy/"
  base = ""
end

ENV['JEKYLL_ENV'] = 'development'
ENV['PAGES_REPO_NWO'] = ""
system(%{bundle exec jekyll serve -I -s #{source} --config ./_config.yml,#{source}/_config_version.yml -b "#{base}" -d "#{destination}"})
